name: Update FXB's National Black Reparations Map data and deploy

on:
  push:
    branches:
      [main] # Run only on main branch pushes
      #- '**' # Trigger on all branches
  schedule:
    - cron: '0 * * * *' # Run every hour (for testing)
    # - cron: '0 8 * * *' # Daily at 8 AM UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Fetch latest data from Airtable
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
        run: |
          echo "Fetching data from Airtable..."
          node src/scripts/fetch-data.js
          echo "Checking if mapdata.json was created..."
          ls -la static/
          echo "Checking file size..."
          stat static/mapdata.json || echo "mapdata.json not found"

      - name: Build site
        run: |
          echo "Building site..."
          npm run build
          echo "Checking build output..."
          ls -la build/
          echo "Looking for mapdata.json in build..."
          find build/ -name "mapdata.json" -ls || echo "mapdata.json not found in build"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
